[webservers]
web-1   ansible_host=   fqdn=bg0dm817qldpbm6vmsr1.auto.internal
web-2   ansible_host=   fqdn=bg01et0pdfqkq4l5ibhk.auto.internal

[databases]
main   ansible_host=   fqdn=bg0pk6h0n04kp1u1o3en.auto.internal
replica   ansible_host=   fqdn=bg0a23krl9aef9qeovjo.auto.internal

[storage]
storage   ansible_host=   fqdn=bg0n89g0hftsnhdpaf1f.auto.internal
