[webservers]
web-1   ansible_host=217.198.171.180   fqdn=bg0fhucliq7642nrvs8m.auto.internal
web-2   ansible_host=217.198.170.243   fqdn=bg0hiqf0ptansvlil94v.auto.internal

[databases]
main   ansible_host=217.198.171.190   fqdn=bg0cp1jrsfq7ahkko0a2.auto.internal
replica   ansible_host=217.198.171.66   fqdn=bg0kgkbp5f64s8itcunk.auto.internal

[storage]
storage   ansible_host=217.198.168.152   fqdn=bg032ds99o3m3f6ha7vi.auto.internal
